check points for distance instead
hypar-io/HyparSpace pull request #101
Opened 2024-06-12 14:38 UTC by jamesbradleym

Evidently using the distance from one line to another was not sufficient to determine if projection was needed. This PR compares the end points of the lines for to determine if they are within tolerance, but further than epsilon, and thus needs projection.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/101)

2024-06-18 20:13 UTC, wynged requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/101)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @jamesbradleym)

___
*[`LayoutFunctions/WallsLOD200/src/WallsLOD200.cs` line 128 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/101#-O-gy16d22DO339dfxP3:-O-gy16d22DO339dfxP4:b-n1nawq) ([raw file](https://github.com/hypar-io/HyparSpace/blob/d108826e2671f1d401c5f494aea85cb0acba6752/LayoutFunctions/WallsLOD200/src/WallsLOD200.cs#L128)):*
> ```Smalltalk
>                             {
>                                 // project lines with points within tolerance of eachother but further than epsilon
>                                 if (LinesWithinTolerance(line, otherLine, tolerance))
> ```

I'm having trouble figuring what we've fundamentally changed and be sure we're not discarding something we might want to join.

like, what if there are two lines that overlap where the overlap is greater than tolerance, they won't pass the new check right, because their endpoints aren't close enough.  is that what we want?

Can you help me understand the failure mode of the original code better?


<!-- Sent from Reviewable.io -->

2024-06-18 20:27 UTC, jamesbradleym commented
Well we only want to join things that are within tolerance of one another, that's the fuzzy distance we're defining as "The user is intending to join these but they just didn't perfectly snap the spaces together to get a straight wall". 

If two lines overlap they do not require projection to be successfully merged with `MergedCollinearLine`. It doesn't matter that those end points are not within tolerance because they don't need projection and are already in the flow of being merged after passing:
`if (line.TryGetOverlap(otherLine, out var overlap) || line.DistanceTo(otherLine) < tolerance)`

The original code failed because judging the distance between two lines did not provide a distance that triggered the need for projection even though the line was off axis, aka was a distance between epsilon and tolerance.

2024-06-19 20:53 UTC, wynged requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/101)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @jamesbradleym)

___
*[`LayoutFunctions/WallsLOD200/src/WallsLOD200.cs` line 128 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/101#-O-gy16d22DO339dfxP3:-O-mGKom2V4egiaLla5K:b-7rl0jd) ([raw file](https://github.com/hypar-io/HyparSpace/blob/d108826e2671f1d401c5f494aea85cb0acba6752/LayoutFunctions/WallsLOD200/src/WallsLOD200.cs#L128)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I'm having trouble figuring what we've fundamentally changed and be sure we're not discarding something we might want to join.

like, what if there are two lines that overlap where the overlap is greater than tolerance, they won't pass the new check right, because their endpoints aren't close enough.  is that what we want?

Can you help me understand the failure mode of the original code better?
</blockquote></details>

done.
___
*[`LayoutFunctions/WallsLOD200/src/WallsLOD200.cs` line 127 at r2](https://reviewable.io/reviews/hypar-io/HyparSpace/101#-O-mGQ_4C094BhoH2Nhv:-O-mGQ_4C094BhoH2Nhw:b-35uet9) ([raw file](https://github.com/hypar-io/HyparSpace/blob/b750b862a5e1c634203551cc8d82db16723bd0e6/LayoutFunctions/WallsLOD200/src/WallsLOD200.cs#L127)):*
> ```Smalltalk
>                                 // we project the lines because line.IsCollinear resolves to true on
>                                 // near 0 differences which MergedCollinearLine does not tolerate
>                                 // line.DistanceTo is similarly fuzzy and resolves to 0 on near (but greater than epsilon) distances
> ```

might not need this last line of the comment, unless you're going to add a note that this is why we're  not using that method to determine if projection is necessary.


<!-- Sent from Reviewable.io -->

2024-06-19 20:53 UTC, wynged approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/101)* status: 1 of 1 approvals obtained, 1 unresolved discussion (waiting on @jamesbradleym)



<!-- Sent from Reviewable.io -->

2024-06-19 20:57 UTC, merged