Add Travel Distance Analyzer function.
hypar-io/HyparSpace pull request #79
Opened 2023-12-07 15:43 UTC by DmytroMuravskyi

New function have two model:
- Calculate route between a set of destinations.
- Calculate distance statistics from a point of rooms of 1 or more types.

Routes are visualized as representation instances and visible when selected.

Function works or without doors
- When doors are present, only doors and any open parts of room boundaries, touching a corridor, are used as exits. Multiple exits per side is supported.
- When they are not present - if room side has open passage - it's used. Otherwise midpoint of wall portion that touches a corridor is considered an exit.

Future work:
- Distance calculation function is using recursion that can lead to stack overflow if room layout is very large. It will be replaced by loop based function when initial feedback is received.

![image](https://github.com/hypar-io/HyparSpace/assets/22522160/d91e6379-f210-4c75-b6de-85f9ce3fd8bd)

2023-12-13 15:33 UTC, katehryhorenko requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79)* status: 1 change requests, 0 of 1 approvals obtained, 8 unresolved discussions (waiting on @DmytroMuravskyi)

___
*[`TravelDistanceAnalyzer/dependencies/CirculationSegment.g.cs` line 1 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYiHtR1IxUxiexOoi2:-NlYiHtR1IxUxiexOoi3:bwhppdi) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/dependencies/CirculationSegment.g.cs#L1)):*
> ```Smalltalk
> //----------------------
> ```

Please add *.g.cs files to the ignore list
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjNpK3uiBrGPVpqz9:-NlYjNpK3uiBrGPVpqzA:blpq8o1) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
> ```Smalltalk
>         public AdaptiveGrid Build(IEnumerable<CirculationSegment> corridors,
>                                   IEnumerable<SpaceBoundary> rooms,
>                                   List<WallCandidate>? walls = null,
> ```

Why do you need to make List<WallCandidate> and    List<Door> nullable? List is a reference type and can be null
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjiFd45_gIWJdqNyw:-NlYjiFd45_gIWJdqNyx:bxoqp7a) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
> ```Smalltalk
>         public AdaptiveGrid Build(IEnumerable<CirculationSegment> corridors,
>                                   IEnumerable<SpaceBoundary> rooms,
>                                   List<WallCandidate>? walls = null,
> ```

Can it be IEnumerable<WallCandidate> and IEnumerable<Door>?
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjyHh09C0DuYMTRe9:-NlYjyHh09C0DuYMTReA:b-hntnkg) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L67)):*
> ```Smalltalk
>             foreach (var room in _roomExits)
>             {
>                 var p = room.Key.Boundary.Perimeter.TransformedPolygon(room.Key.Transform);
> ```

Try to alwaays use meaningful names (e.g. 'polygon' or 'roomBoundary' instead of 'p')
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYlhlv6rhNV9K5SCsk:-NlYlhlv6rhNV9K5SCsl:b-qzijci) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L113)):*
> ```Smalltalk
>             }
> 
>             var mainConnection = _grid.GetVertex(exit.Edges.First().OtherVertexId(exit.Id));
> ```

Are you sure that exit.Edges always has at least one value? Maybe it makes sense to add an additional verification:

  



_Code snippet:_
```Smalltalk
if (exit.Edges.Count > 2 || exit.Edges.Count < 1)
{
    return;
}
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 148 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYmY9X1lR4CJLq0DVX:-NlYmY9X1lR4CJLq0DVY:bgk7cgx) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L148)):*
> ```Smalltalk
>                 var directionIndex = -1;
>                 var dot = delta.Unitized().Dot(xDir);
>                 if (dot.ApproximatelyEquals(1, 0.01))
> ```

create a private tolerance const with 0.01 value 
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 197 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYktkf8FFcn-WxPWRD:-NlYktkf8FFcn-WxPWRE:bn2vesz) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L197)):*
> ```Smalltalk
>         }
> 
>         private Edge? ClosestEdgeOnElevation(Vector3 location, out Vector3 point)
> ```

It is better to add the action name into the function name. 

Edge? FindClosestEdgeOnElevation(Vector3 location, out Vector3 point)
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 243 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYnI6U89ya35G__FE-:-NlYnI6U89ya35G__FE0:b-3o1pi) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L243)):*
> ```Smalltalk
>         /// <param name="centerlines">Corridor segments with precalculated center lines.</param>
>         /// <param name="grid">AdaptiveGrid to insert new vertices and edge into.</param>
>         private void Intersect(List<(CirculationSegment Segment, Polyline Centerline)> centerlines)
> ```

CreateConnectionEdges or CreateIntersections


<!-- Sent from Reviewable.io -->

2023-12-13 16:30 UTC, DmytroMuravskyi reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79)* status: 1 change requests, 0 of 1 approvals obtained, 8 unresolved discussions (waiting on @katehryhorenko)

___
*[`TravelDistanceAnalyzer/dependencies/CirculationSegment.g.cs` line 1 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYiHtR1IxUxiexOoi2:-NlYxdoJ69wDGV5Vdxxd:b8vwz81) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/dependencies/CirculationSegment.g.cs#L1)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Please add *.g.cs files to the ignore list
</blockquote></details>

HyparSpace stores *.g.cs in all functions. There is actually a benefit to that as every commit can be built even if schema is changed.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjNpK3uiBrGPVpqz9:-NlYv-EKDrcpWvLY9Eab:bewp262) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Why do you need to make List<WallCandidate> and    List<Door> nullable? List is a reference type and can be null
</blockquote></details>

It's to prevent the warnings, I wanted the function to have 0 warnings and when null is assigned to non nullable type - compiler always produces one.  There is also a logical difference: if walls null - Walls function is not in workflow. If empty list - function is there but there are no walls. The same is true for doors.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjiFd45_gIWJdqNyw:-NlYyLqyAImn4zCuGW66:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Can it be IEnumerable<WallCandidate> and IEnumerable<Door>?
</blockquote></details>

Done.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjyHh09C0DuYMTRe9:-NlYyLON-nMdzWjUJ8Vz:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L67)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Try to alwaays use meaningful names (e.g. 'polygon' or 'roomBoundary' instead of 'p')
</blockquote></details>

Done.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYlhlv6rhNV9K5SCsk:-NlYyWwE--otr4FYDwWQ:b-8pwso) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L113)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Are you sure that exit.Edges always has at least one value? Maybe it makes sense to add an additional verification:
</blockquote></details>

Grid should not have free vertices, this is exceptional situation. If this is possible, I want the exception, and not silent return.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 148 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYmY9X1lR4CJLq0DVX:-NlYzNMa7UaEtyTPWs51:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L148)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

create a private tolerance const with 0.01 value
</blockquote></details>

Done.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 197 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYktkf8FFcn-WxPWRD:-NlZ-2hG54kFvp8zx7rX:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L197)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

It is better to add the action name into the function name. 

Edge? FindClosestEdgeOnElevation(Vector3 location, out Vector3 point)
</blockquote></details>

Done.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 243 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYnI6U89ya35G__FE-:-NlYzebV7dy9OIEi6DlE:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L243)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

CreateConnectionEdges or CreateIntersections
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 20:57 UTC, katehryhorenko requested changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79)* status: 1 change requests, 0 of 1 approvals obtained, 8 unresolved discussions (waiting on @DmytroMuravskyi)

___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjNpK3uiBrGPVpqz9:-NlZqAA291BnA2fdDK25:b-p1pnp8) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

It's to prevent the warnings, I wanted the function to have 0 warnings and when null is assigned to non nullable type - compiler always produces one.  There is also a logical difference: if walls null - Walls function is not in workflow. If empty list - function is there but there are no walls. The same is true for doors.
</blockquote></details>

I see. So id you are planning to call Build method only with two input parameters (Build(corridors, rooms)), then yes, it's a correct approach. But I can see why you are getting the warning. Lets talk tomorrow :)
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYlhlv6rhNV9K5SCsk:-NlZxJzY2khxYgy5RgWD:b-x548bz) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L113)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Grid should not have free vertices, this is exceptional situation. If this is possible, I want the exception, and not silent return.
</blockquote></details>

Then it's better to check the edges count and throw the exception  at the begin  of the function. You don't need to wait for exit.Edges.First() throw an exception


<!-- Sent from Reviewable.io -->

2023-12-14 09:16 UTC, DmytroMuravskyi reviewed
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79)* status: 1 change requests, 0 of 1 approvals obtained, 8 unresolved discussions (waiting on @katehryhorenko)

___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 32 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYjNpK3uiBrGPVpqz9:-Nlb_gn54opCLMMbfmvg:b3dxc33) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L32)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

I see. So id you are planning to call Build method only with two input parameters (Build(corridors, rooms)), then yes, it's a correct approach. But I can see why you are getting the warning. Lets talk tomorrow :)
</blockquote></details>

Yes, let's discuss. No, it's not about default input parameters, I removed them, as they are no longer used. It's about optional model dependencies: when doors or walls are not there they are null and this is much cleaner than empty list.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 113 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlYlhlv6rhNV9K5SCsk:-Nlb_TGBEKH58P-AUCgg:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/9dad486422ba29ac9f28f8d7f517d15bd84b90c3/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L113)):*
<details><summary><i>Previously, katehryhorenko (Kateryna Hryhorenko) wrote…</i></summary><blockquote>

Then it's better to check the edges count and throw the exception  at the begin  of the function. You don't need to wait for exit.Edges.First() throw an exception
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-18 20:33 UTC, katehryhorenko requested changes
Hey! Overall looks good! 
I added a few comments - suggestions. You can ignore them.

I few comments that I would ask you to fix:
- Keep the order of the class members. My suggestion is
{
private cons
private fields
constructor
public properties
public methods
private methods
}
But do not mix public methods and private methods :)
- Some methods have comments for parameters that these methods do not have.

Comments on anything public are welcome!

> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-:-Nly_sUa4W4GLh3Qk97N:bmfi8hy)* status: 1 change requests, 0 of 1 approvals obtained, 11 unresolved discussions (waiting on @DmytroMuravskyi)

___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 104 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxHqgG2CV1HCIWk6eI:-NlxHqgG2CV1HCIWk6eJ:b-f2slnz) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L104)):*
> ```Smalltalk
>                 }
>             }
>             return exitVertex == null ? 0u : exitVertex.Id;
> ```

It's an alternative: exitVertex?.Id ?? 0u
 But it's up to you what to use :)



_Code quote:_
```Smalltalk
exitVertex == null ? 0u : exitVertex.Id
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 248 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlyHqtZ2SCCXa9h6ITW:-NlyHqtZ2SCCXa9h6ITX:b-xjpitj) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L248)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="centerlines">Corridor segments with precalculated center lines.</param>
>         /// <param name="grid">AdaptiveGrid to insert new vertices and edge into.</param>
> ```

Method doesn't have 'grid'  input parameter
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 302 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxJY8IEEyUFRsdTjb4:-NlxJY8IEEyUFRsdTjb5:b-w7qi0e) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L302)):*
> ```Smalltalk
>                         }
> 
>                         if (closestLeftProximity == -1 || closestRightProximity == -1)
> ```

Just a suggestion



_Code snippet:_
```Smalltalk
private const int InvalidProximity = -1;
private const int MaxProximityDifference = 2;

// ...

if (closestLeftProximity == InvalidProximity || closestRightProximity == InvalidProximity)
{
    continue;
}
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 375 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxVQRh52ngd_5c3QQM:-NlxVQRh52ngd_5c3QQN:bxncujr) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L375)):*
> ```Smalltalk
>         }
> 
>         private Edge? FindOnCollinearEdges(GridVertex start, ulong endId, Vector3 direction, Vector3 destination)
> ```

FindCollinearEdgeTowardsEndpoin



_Code quote:_
```Smalltalk
 FindOnCollinearEdges
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 379 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxVaKh2ScV5Mg_jQ0m:-NlxVaKh2ScV5Mg_jQ0n:b-ejkmgn) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L379)):*
> ```Smalltalk
>             while (start.Id != endId)
>             {
>                 GridVertex otherVertex = start;
> ```

The variable name `otherVertex` might be misleading because it's actually the next vertex in the loop. Consider renaming it to something like `nextVertex` for clarity.
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 428 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxWGTfDDnq17Znz0Gb:-NlxWGTfDDnq17Znz0Gc:bb7k22h) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L428)):*
> ```Smalltalk
>         }
> 
>         private void ExtendToCorridor(Line l, CirculationSegment segment)
> ```

line



_Code quote:_
```Smalltalk
l
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 436 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxWg_o-_CZP35ZRykV:-NlxWg_p72p_VyXdklpS:b79qxd) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L436)):*
> ```Smalltalk
>                 var trimLine = new Line(l.Start - l.Direction() * maxDistance,
>                                         l.End + l.Direction() * maxDistance);
>                 var inside = trimLine.Trim(transformedPolygon, out _);
> ```

intersectionLines



_Code quote:_
```Smalltalk
inside
```
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 454 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxWvVY17ntwkXNUJ3-:-NlxWvVY17ntwkXNUJ30:bj39s7d) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L454)):*
> ```Smalltalk
>         /// </summary>
>         /// <param name="room">Room geometry.</param>
>         /// <param name="centerlines">Corridor segments with precalculated center lines.</param>
> ```

Please fix the comment. 'grid' and 'centerLines' parameters do not exist :)
___
*[`TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs` line 462 at r4](https://reviewable.io/reviews/hypar-io/HyparSpace/79#-NlxdVCk6ZMuSLbvyTHu:-NlxdVCk6ZMuSLbvyTHv:bet77hz) ([raw file](https://github.com/hypar-io/HyparSpace/blob/aaca8f04cf3649c71cca827737c4a9a6ea8cfe50/TravelDistanceAnalyzer/src/AdaptiveGridBuilder.cs#L462)):*
> ```Smalltalk
>             IEnumerable<Door>? doors)
>         {
>             var roomExits = new List<GridVertex>();
> ```

roomExitVertices



_Code quote:_
```Smalltalk
roomExits
```


<!-- Sent from Reviewable.io -->

2023-12-20 17:46 UTC, katehryhorenko approved these changes
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/79)* status: 1 of 1 approvals obtained, 10 unresolved discussions (waiting on @DmytroMuravskyi)



<!-- Sent from Reviewable.io -->

2023-12-20 17:46 UTC, merged